#====================================#
# Syslog Windows Agent Configuration #
#====================================#
# Syslog server wich will receive every log
Server: 127.0.0.1

# Mode debug permit to see every filtered log
Mode: Debug

# Active temp file log in the root of exe
EnableLog: true

# Define the number of line max before rewrite on it
LogLineMax: 5000

# Define the path for the templates
TemplatePath: "./templates"